In [13]:
from __future__ import print_function
import torch
import numpy as np

In [6]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7197, 0.5983, 1.4319],
        [1.0495, 0.6888, 0.9521],
        [0.8031, 0.7659, 1.0351],
        [0.2876, 1.8858, 0.9692],
        [1.4368, 1.7514, 1.5754]])


In [24]:
# converting a Torch Tensor to Numpy Array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

# converting a Numpy Array to a Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
